/*
Navicat PGSQL Data Transfer

Source Server         : desenvolvimento
Source Server Version : 90204
Source Host           : localhost:5432
Source Database       : indeorum
Source Schema         : public

Target Server Type    : PGSQL
Target Server Version : 90204
File Encoding         : 65001

Date: 2019-02-22 06:24:45
*/


-- ----------------------------
-- Table structure for trabalhos
-- ----------------------------
DROP TABLE IF EXISTS "public"."trabalhos";
CREATE TABLE "public"."trabalhos" (
"id" int4 DEFAULT nextval('jobs_id_seq'::regclass) NOT NULL,
"descricao" varchar(150) COLLATE "default"
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of trabalhos
-- ----------------------------
INSERT INTO "public"."trabalhos" VALUES ('4', 'Insurance broker');
INSERT INTO "public"."trabalhos" VALUES ('5', 'Interpreter');
INSERT INTO "public"."trabalhos" VALUES ('6', 'Geophysical data processor');
INSERT INTO "public"."trabalhos" VALUES ('7', 'Futures trader');
INSERT INTO "public"."trabalhos" VALUES ('8', 'Therapist, occupational');
INSERT INTO "public"."trabalhos" VALUES ('9', 'Counselling psychologist');
INSERT INTO "public"."trabalhos" VALUES ('10', 'Surveyor, building control');
INSERT INTO "public"."trabalhos" VALUES ('11', 'Psychologist, sport and exercise');
INSERT INTO "public"."trabalhos" VALUES ('12', 'Surgeon');
INSERT INTO "public"."trabalhos" VALUES ('13', 'Drilling engineer');
INSERT INTO "public"."trabalhos" VALUES ('14', 'Professor Emeritus');
INSERT INTO "public"."trabalhos" VALUES ('15', 'Scientist, research (physical sciences)');
INSERT INTO "public"."trabalhos" VALUES ('16', 'Designer, graphic');
INSERT INTO "public"."trabalhos" VALUES ('17', 'Hospital doctor');
INSERT INTO "public"."trabalhos" VALUES ('18', 'Office manager');
INSERT INTO "public"."trabalhos" VALUES ('19', 'General practice doctor');
INSERT INTO "public"."trabalhos" VALUES ('20', 'Surveyor, mining');
INSERT INTO "public"."trabalhos" VALUES ('21', 'Materials engineer');
INSERT INTO "public"."trabalhos" VALUES ('22', 'Financial risk analyst');
INSERT INTO "public"."trabalhos" VALUES ('23', 'Insurance claims handler');
INSERT INTO "public"."trabalhos" VALUES ('24', 'Engineer, production');
INSERT INTO "public"."trabalhos" VALUES ('25', 'Horticultural therapist');
INSERT INTO "public"."trabalhos" VALUES ('26', 'Pharmacist, community');
INSERT INTO "public"."trabalhos" VALUES ('27', 'Automotive engineer');
INSERT INTO "public"."trabalhos" VALUES ('28', 'Teacher, adult education');
INSERT INTO "public"."trabalhos" VALUES ('29', 'Information officer');
INSERT INTO "public"."trabalhos" VALUES ('30', 'Energy engineer');
INSERT INTO "public"."trabalhos" VALUES ('31', 'Medical secretary');
INSERT INTO "public"."trabalhos" VALUES ('32', 'Operational investment banker');
INSERT INTO "public"."trabalhos" VALUES ('33', 'Economist');
INSERT INTO "public"."trabalhos" VALUES ('34', 'Ecologist');
INSERT INTO "public"."trabalhos" VALUES ('35', 'Patent examiner');
INSERT INTO "public"."trabalhos" VALUES ('36', 'Data scientist');
INSERT INTO "public"."trabalhos" VALUES ('37', 'Audiological scientist');
INSERT INTO "public"."trabalhos" VALUES ('38', 'Retail banker');
INSERT INTO "public"."trabalhos" VALUES ('39', 'Art gallery manager');
INSERT INTO "public"."trabalhos" VALUES ('40', 'Research scientist (life sciences)');
INSERT INTO "public"."trabalhos" VALUES ('41', 'Risk manager');
INSERT INTO "public"."trabalhos" VALUES ('42', 'Chiropodist');
INSERT INTO "public"."trabalhos" VALUES ('43', 'Air broker');
INSERT INTO "public"."trabalhos" VALUES ('44', 'Travel agency manager');
INSERT INTO "public"."trabalhos" VALUES ('45', 'Chiropractor');
INSERT INTO "public"."trabalhos" VALUES ('46', 'Environmental education officer');
INSERT INTO "public"."trabalhos" VALUES ('47', 'Engineer, drilling');
INSERT INTO "public"."trabalhos" VALUES ('48', 'Broadcast journalist');
INSERT INTO "public"."trabalhos" VALUES ('49', 'Public relations account executive');
INSERT INTO "public"."trabalhos" VALUES ('50', 'Artist');
INSERT INTO "public"."trabalhos" VALUES ('51', 'Surveyor, planning and development');
INSERT INTO "public"."trabalhos" VALUES ('52', 'Fast food restaurant manager');
INSERT INTO "public"."trabalhos" VALUES ('53', 'Maintenance engineer');
INSERT INTO "public"."trabalhos" VALUES ('54', 'Child psychotherapist');
INSERT INTO "public"."trabalhos" VALUES ('55', 'Curator');
INSERT INTO "public"."trabalhos" VALUES ('56', 'Volunteer coordinator');
INSERT INTO "public"."trabalhos" VALUES ('57', 'Engineer, chemical');
INSERT INTO "public"."trabalhos" VALUES ('58', 'Chartered legal executive (England and Wales)');
INSERT INTO "public"."trabalhos" VALUES ('59', 'Scientist, research (medical)');
INSERT INTO "public"."trabalhos" VALUES ('60', 'Broadcast engineer');
INSERT INTO "public"."trabalhos" VALUES ('61', 'Video editor');
INSERT INTO "public"."trabalhos" VALUES ('62', 'Water quality scientist');
INSERT INTO "public"."trabalhos" VALUES ('63', 'Aeronautical engineer');
INSERT INTO "public"."trabalhos" VALUES ('64', 'Editor, magazine features');
INSERT INTO "public"."trabalhos" VALUES ('65', 'Rural practice surveyor');
INSERT INTO "public"."trabalhos" VALUES ('66', 'Civil Service fast streamer');
INSERT INTO "public"."trabalhos" VALUES ('67', 'Secretary/administrator');
INSERT INTO "public"."trabalhos" VALUES ('68', 'Financial controller');
INSERT INTO "public"."trabalhos" VALUES ('69', 'Industrial buyer');
INSERT INTO "public"."trabalhos" VALUES ('70', 'Personal assistant');
INSERT INTO "public"."trabalhos" VALUES ('71', 'Dramatherapist');
INSERT INTO "public"."trabalhos" VALUES ('72', 'Producer, radio');
INSERT INTO "public"."trabalhos" VALUES ('73', 'Metallurgist');
INSERT INTO "public"."trabalhos" VALUES ('74', 'Visual merchandiser');
INSERT INTO "public"."trabalhos" VALUES ('75', 'Passenger transport manager');
INSERT INTO "public"."trabalhos" VALUES ('76', 'Planning and development surveyor');
INSERT INTO "public"."trabalhos" VALUES ('77', 'Homeopath');
INSERT INTO "public"."trabalhos" VALUES ('78', 'Scientist, water quality');
INSERT INTO "public"."trabalhos" VALUES ('79', 'Editorial assistant');
INSERT INTO "public"."trabalhos" VALUES ('80', 'Surveyor, rural practice');
INSERT INTO "public"."trabalhos" VALUES ('81', 'Surveyor, quantity');
INSERT INTO "public"."trabalhos" VALUES ('82', 'Advertising copywriter');
INSERT INTO "public"."trabalhos" VALUES ('83', 'Environmental health practitioner');
INSERT INTO "public"."trabalhos" VALUES ('84', 'Music tutor');
INSERT INTO "public"."trabalhos" VALUES ('85', 'Psychotherapist, child');
INSERT INTO "public"."trabalhos" VALUES ('86', 'Production assistant, television');
INSERT INTO "public"."trabalhos" VALUES ('87', 'Engineer, water');
INSERT INTO "public"."trabalhos" VALUES ('88', 'IT consultant');
INSERT INTO "public"."trabalhos" VALUES ('89', 'Camera operator');
INSERT INTO "public"."trabalhos" VALUES ('90', 'Product/process development scientist');
INSERT INTO "public"."trabalhos" VALUES ('91', 'Press sub');
INSERT INTO "public"."trabalhos" VALUES ('92', 'Software engineer');
INSERT INTO "public"."trabalhos" VALUES ('93', 'Teaching laboratory technician');
INSERT INTO "public"."trabalhos" VALUES ('94', 'Chief Technology Officer');
INSERT INTO "public"."trabalhos" VALUES ('95', 'Physiotherapist');
INSERT INTO "public"."trabalhos" VALUES ('96', 'Bonds trader');
INSERT INTO "public"."trabalhos" VALUES ('97', 'Research scientist (medical)');
INSERT INTO "public"."trabalhos" VALUES ('98', 'Armed forces operational officer');
INSERT INTO "public"."trabalhos" VALUES ('99', 'Oncologist');
INSERT INTO "public"."trabalhos" VALUES ('100', 'Teacher, music');
INSERT INTO "public"."trabalhos" VALUES ('101', 'Architectural technologist');
INSERT INTO "public"."trabalhos" VALUES ('102', 'Special educational needs teacher');
INSERT INTO "public"."trabalhos" VALUES ('103', 'Scientist, research (maths)');
INSERT INTO "public"."trabalhos" VALUES ('104', 'Therapist, nutritional');
INSERT INTO "public"."trabalhos" VALUES ('105', 'Administrator');
INSERT INTO "public"."trabalhos" VALUES ('106', 'Accountant, chartered public finance');
INSERT INTO "public"."trabalhos" VALUES ('107', 'Colour technologist');
INSERT INTO "public"."trabalhos" VALUES ('108', 'Actuary');
INSERT INTO "public"."trabalhos" VALUES ('109', 'Oceanographer');
INSERT INTO "public"."trabalhos" VALUES ('110', 'Senior tax professional/tax inspector');
INSERT INTO "public"."trabalhos" VALUES ('111', 'Private music teacher');
INSERT INTO "public"."trabalhos" VALUES ('112', 'Civil engineer, consulting');
INSERT INTO "public"."trabalhos" VALUES ('113', 'Adult nurse');
INSERT INTO "public"."trabalhos" VALUES ('114', 'Youth worker');
INSERT INTO "public"."trabalhos" VALUES ('115', 'Research officer, government');
INSERT INTO "public"."trabalhos" VALUES ('116', 'Dance movement psychotherapist');
INSERT INTO "public"."trabalhos" VALUES ('117', 'Media buyer');
INSERT INTO "public"."trabalhos" VALUES ('118', 'Social research officer, government');
INSERT INTO "public"."trabalhos" VALUES ('119', 'Communications engineer');
INSERT INTO "public"."trabalhos" VALUES ('120', 'Systems developer');
INSERT INTO "public"."trabalhos" VALUES ('121', 'Designer, interior/spatial');
INSERT INTO "public"."trabalhos" VALUES ('122', 'Neurosurgeon');
INSERT INTO "public"."trabalhos" VALUES ('123', 'Legal executive');
INSERT INTO "public"."trabalhos" VALUES ('124', 'Tour manager');
INSERT INTO "public"."trabalhos" VALUES ('125', 'Hotel manager');
INSERT INTO "public"."trabalhos" VALUES ('126', 'IT trainer');
INSERT INTO "public"."trabalhos" VALUES ('127', 'Midwife');
INSERT INTO "public"."trabalhos" VALUES ('128', 'Press photographer');
INSERT INTO "public"."trabalhos" VALUES ('129', 'Engineer, energy');
INSERT INTO "public"."trabalhos" VALUES ('130', 'Writer');
INSERT INTO "public"."trabalhos" VALUES ('131', 'Lawyer');
INSERT INTO "public"."trabalhos" VALUES ('132', 'Industrial/product designer');
INSERT INTO "public"."trabalhos" VALUES ('133', 'Heritage manager');
INSERT INTO "public"."trabalhos" VALUES ('134', 'Engineer, maintenance');
INSERT INTO "public"."trabalhos" VALUES ('135', 'Designer, ceramics/pottery');
INSERT INTO "public"."trabalhos" VALUES ('136', 'Building control surveyor');
INSERT INTO "public"."trabalhos" VALUES ('137', 'Training and development officer');
INSERT INTO "public"."trabalhos" VALUES ('138', 'Best boy');
INSERT INTO "public"."trabalhos" VALUES ('139', 'Designer, blown glass/stained glass');
INSERT INTO "public"."trabalhos" VALUES ('140', 'Forensic scientist');
INSERT INTO "public"."trabalhos" VALUES ('141', 'Freight forwarder');
INSERT INTO "public"."trabalhos" VALUES ('142', 'Public affairs consultant');
INSERT INTO "public"."trabalhos" VALUES ('143', 'Therapist, speech and language');
INSERT INTO "public"."trabalhos" VALUES ('144', 'Charity officer');
INSERT INTO "public"."trabalhos" VALUES ('145', 'Transport planner');
INSERT INTO "public"."trabalhos" VALUES ('146', 'Conference centre manager');
INSERT INTO "public"."trabalhos" VALUES ('147', 'Health promotion specialist');
INSERT INTO "public"."trabalhos" VALUES ('148', 'Quantity surveyor');
INSERT INTO "public"."trabalhos" VALUES ('149', 'Retail buyer');
INSERT INTO "public"."trabalhos" VALUES ('150', 'Acupuncturist');
INSERT INTO "public"."trabalhos" VALUES ('151', 'Contracting civil engineer');
INSERT INTO "public"."trabalhos" VALUES ('152', 'Chartered public finance accountant');
INSERT INTO "public"."trabalhos" VALUES ('153', 'Banker');
INSERT INTO "public"."trabalhos" VALUES ('154', 'Historic buildings inspector/conservation officer');
INSERT INTO "public"."trabalhos" VALUES ('155', 'Museum/gallery conservator');
INSERT INTO "public"."trabalhos" VALUES ('156', 'Recruitment consultant');
INSERT INTO "public"."trabalhos" VALUES ('157', 'Animator');
INSERT INTO "public"."trabalhos" VALUES ('158', 'Psychologist, counselling');
INSERT INTO "public"."trabalhos" VALUES ('159', 'Museum education officer');
INSERT INTO "public"."trabalhos" VALUES ('160', 'Bookseller');
INSERT INTO "public"."trabalhos" VALUES ('161', 'Buyer, retail');
INSERT INTO "public"."trabalhos" VALUES ('162', 'Event organiser');
INSERT INTO "public"."trabalhos" VALUES ('163', 'Musician');
INSERT INTO "public"."trabalhos" VALUES ('164', 'Customer service manager');
INSERT INTO "public"."trabalhos" VALUES ('165', 'Speech and language therapist');
INSERT INTO "public"."trabalhos" VALUES ('166', 'Multimedia programmer');
INSERT INTO "public"."trabalhos" VALUES ('167', 'Psychologist, forensic');
INSERT INTO "public"."trabalhos" VALUES ('168', 'Buyer, industrial');
INSERT INTO "public"."trabalhos" VALUES ('169', 'Illustrator');
INSERT INTO "public"."trabalhos" VALUES ('170', 'Community pharmacist');
INSERT INTO "public"."trabalhos" VALUES ('171', 'Scientist, physiological');
INSERT INTO "public"."trabalhos" VALUES ('172', 'Nurse, mental health');
INSERT INTO "public"."trabalhos" VALUES ('173', 'Doctor, hospital');
INSERT INTO "public"."trabalhos" VALUES ('174', 'Art therapist');
INSERT INTO "public"."trabalhos" VALUES ('175', 'Financial trader');
INSERT INTO "public"."trabalhos" VALUES ('176', 'Chief Marketing Officer');
INSERT INTO "public"."trabalhos" VALUES ('177', 'Fine artist');
INSERT INTO "public"."trabalhos" VALUES ('178', 'Microbiologist');
INSERT INTO "public"."trabalhos" VALUES ('179', 'Make');
INSERT INTO "public"."trabalhos" VALUES ('180', 'Mental health nurse');
INSERT INTO "public"."trabalhos" VALUES ('181', 'Exercise physiologist');
INSERT INTO "public"."trabalhos" VALUES ('182', 'Librarian, academic');
INSERT INTO "public"."trabalhos" VALUES ('183', 'Designer, industrial/product');
INSERT INTO "public"."trabalhos" VALUES ('184', 'Designer, exhibition/display');
INSERT INTO "public"."trabalhos" VALUES ('185', 'Education administrator');
INSERT INTO "public"."trabalhos" VALUES ('186', 'Horticulturist, amenity');
INSERT INTO "public"."trabalhos" VALUES ('187', 'Publishing rights manager');
INSERT INTO "public"."trabalhos" VALUES ('188', 'Agricultural consultant');
INSERT INTO "public"."trabalhos" VALUES ('189', 'Diplomatic Services operational officer');
INSERT INTO "public"."trabalhos" VALUES ('190', 'Teacher, primary school');
INSERT INTO "public"."trabalhos" VALUES ('191', 'Journalist, newspaper');
INSERT INTO "public"."trabalhos" VALUES ('192', 'Financial manager');
INSERT INTO "public"."trabalhos" VALUES ('193', 'Radiation protection practitioner');
INSERT INTO "public"."trabalhos" VALUES ('194', 'Early years teacher');
INSERT INTO "public"."trabalhos" VALUES ('195', 'Designer, multimedia');
INSERT INTO "public"."trabalhos" VALUES ('196', 'Television camera operator');
INSERT INTO "public"."trabalhos" VALUES ('197', 'Product manager');
INSERT INTO "public"."trabalhos" VALUES ('198', 'Restaurant manager');
INSERT INTO "public"."trabalhos" VALUES ('199', 'Brewing technologist');
INSERT INTO "public"."trabalhos" VALUES ('200', 'Conservator, museum/gallery');
INSERT INTO "public"."trabalhos" VALUES ('201', 'Arts administrator');
INSERT INTO "public"."trabalhos" VALUES ('202', 'Sports development officer');
INSERT INTO "public"."trabalhos" VALUES ('203', 'Sports coach');
INSERT INTO "public"."trabalhos" VALUES ('204', 'Patent attorney');
INSERT INTO "public"."trabalhos" VALUES ('205', 'Manufacturing systems engineer');
INSERT INTO "public"."trabalhos" VALUES ('206', 'Sub');
INSERT INTO "public"."trabalhos" VALUES ('207', 'Medical physicist');
INSERT INTO "public"."trabalhos" VALUES ('208', 'Production assistant, radio');
INSERT INTO "public"."trabalhos" VALUES ('209', 'Further education lecturer');
INSERT INTO "public"."trabalhos" VALUES ('210', 'Local government officer');
INSERT INTO "public"."trabalhos" VALUES ('211', 'Control and instrumentation engineer');
INSERT INTO "public"."trabalhos" VALUES ('212', 'Herbalist');
INSERT INTO "public"."trabalhos" VALUES ('213', 'Psychotherapist, dance movement');
INSERT INTO "public"."trabalhos" VALUES ('214', 'Architect');
INSERT INTO "public"."trabalhos" VALUES ('215', 'Engineer, building services');
INSERT INTO "public"."trabalhos" VALUES ('216', 'Occupational therapist');
INSERT INTO "public"."trabalhos" VALUES ('217', 'Analytical chemist');
INSERT INTO "public"."trabalhos" VALUES ('218', 'Translator');
INSERT INTO "public"."trabalhos" VALUES ('219', 'Police officer');
INSERT INTO "public"."trabalhos" VALUES ('220', 'Engineer, civil (consulting)');
INSERT INTO "public"."trabalhos" VALUES ('221', 'Secretary, company');
INSERT INTO "public"."trabalhos" VALUES ('222', 'Museum/gallery exhibitions officer');
INSERT INTO "public"."trabalhos" VALUES ('223', 'Engineer, land');
INSERT INTO "public"."trabalhos" VALUES ('224', 'Sports therapist');
INSERT INTO "public"."trabalhos" VALUES ('225', 'Personnel officer');
INSERT INTO "public"."trabalhos" VALUES ('226', 'Ship broker');
INSERT INTO "public"."trabalhos" VALUES ('227', 'Health physicist');
INSERT INTO "public"."trabalhos" VALUES ('228', 'Research scientist (physical sciences)');
INSERT INTO "public"."trabalhos" VALUES ('229', 'Teacher, special educational needs');
INSERT INTO "public"."trabalhos" VALUES ('230', 'Copywriter, advertising');
INSERT INTO "public"."trabalhos" VALUES ('231', 'Mudlogger');
INSERT INTO "public"."trabalhos" VALUES ('232', 'Educational psychologist');
INSERT INTO "public"."trabalhos" VALUES ('233', 'Electronics engineer');
INSERT INTO "public"."trabalhos" VALUES ('234', 'Radio producer');
INSERT INTO "public"."trabalhos" VALUES ('235', 'Astronomer');
INSERT INTO "public"."trabalhos" VALUES ('236', 'Consulting civil engineer');
INSERT INTO "public"."trabalhos" VALUES ('237', 'Geophysicist/field seismologist');
INSERT INTO "public"."trabalhos" VALUES ('238', 'English as a second language teacher');
INSERT INTO "public"."trabalhos" VALUES ('239', 'Doctor, general practice');
INSERT INTO "public"."trabalhos" VALUES ('240', 'Engineer, aeronautical');
INSERT INTO "public"."trabalhos" VALUES ('241', 'Scientist, marine');
INSERT INTO "public"."trabalhos" VALUES ('242', 'Health visitor');
INSERT INTO "public"."trabalhos" VALUES ('243', 'Chartered accountant');
INSERT INTO "public"."trabalhos" VALUES ('244', 'Pensions consultant');
INSERT INTO "public"."trabalhos" VALUES ('245', 'Operational researcher');
INSERT INTO "public"."trabalhos" VALUES ('246', 'Engineer, automotive');
INSERT INTO "public"."trabalhos" VALUES ('247', 'Designer, furniture');
INSERT INTO "public"."trabalhos" VALUES ('248', 'Commissioning editor');
INSERT INTO "public"."trabalhos" VALUES ('249', 'Risk analyst');
INSERT INTO "public"."trabalhos" VALUES ('250', 'Web designer');
INSERT INTO "public"."trabalhos" VALUES ('251', 'Chief Operating Officer');
INSERT INTO "public"."trabalhos" VALUES ('252', 'Geologist, wellsite');
INSERT INTO "public"."trabalhos" VALUES ('253', 'Petroleum engineer');
INSERT INTO "public"."trabalhos" VALUES ('254', 'Development worker, international aid');
INSERT INTO "public"."trabalhos" VALUES ('255', 'IT technical support officer');
INSERT INTO "public"."trabalhos" VALUES ('256', 'Cabin crew');
INSERT INTO "public"."trabalhos" VALUES ('257', 'Sound technician, broadcasting/film/video');
INSERT INTO "public"."trabalhos" VALUES ('258', 'International aid/development worker');
INSERT INTO "public"."trabalhos" VALUES ('259', 'Social researcher');
INSERT INTO "public"."trabalhos" VALUES ('260', 'Human resources officer');
INSERT INTO "public"."trabalhos" VALUES ('261', 'Technical brewer');
INSERT INTO "public"."trabalhos" VALUES ('262', 'Energy manager');
INSERT INTO "public"."trabalhos" VALUES ('263', 'Contractor');
INSERT INTO "public"."trabalhos" VALUES ('264', 'Chief Financial Officer');
INSERT INTO "public"."trabalhos" VALUES ('265', 'Surveyor, building');
INSERT INTO "public"."trabalhos" VALUES ('266', 'Pathologist');
INSERT INTO "public"."trabalhos" VALUES ('267', 'Clinical embryologist');
INSERT INTO "public"."trabalhos" VALUES ('268', 'Gaffer');
INSERT INTO "public"."trabalhos" VALUES ('269', 'Furniture conservator/restorer');
INSERT INTO "public"."trabalhos" VALUES ('270', 'Horticulturist, commercial');
INSERT INTO "public"."trabalhos" VALUES ('271', 'Estate manager/land agent');
INSERT INTO "public"."trabalhos" VALUES ('272', 'Chief Executive Officer');
INSERT INTO "public"."trabalhos" VALUES ('273', 'Claims inspector/assessor');
INSERT INTO "public"."trabalhos" VALUES ('274', 'Horticultural consultant');
INSERT INTO "public"."trabalhos" VALUES ('275', 'Licensed conveyancer');
INSERT INTO "public"."trabalhos" VALUES ('276', 'Engineer, manufacturing');
INSERT INTO "public"."trabalhos" VALUES ('277', 'Garment/textile technologist');
INSERT INTO "public"."trabalhos" VALUES ('278', 'Scientist, biomedical');
INSERT INTO "public"."trabalhos" VALUES ('279', 'Higher education lecturer');
INSERT INTO "public"."trabalhos" VALUES ('280', 'Marine scientist');
INSERT INTO "public"."trabalhos" VALUES ('281', 'Haematologist');
INSERT INTO "public"."trabalhos" VALUES ('282', 'Optometrist');
INSERT INTO "public"."trabalhos" VALUES ('283', 'Chief Strategy Officer');
INSERT INTO "public"."trabalhos" VALUES ('284', 'Cytogeneticist');
INSERT INTO "public"."trabalhos" VALUES ('285', 'Research officer, trade union');
INSERT INTO "public"."trabalhos" VALUES ('286', 'Immigration officer');
INSERT INTO "public"."trabalhos" VALUES ('287', 'Emergency planning/management officer');
INSERT INTO "public"."trabalhos" VALUES ('288', 'Environmental consultant');
INSERT INTO "public"."trabalhos" VALUES ('289', 'Engineer, maintenance (IT)');
INSERT INTO "public"."trabalhos" VALUES ('290', 'Holiday representative');
INSERT INTO "public"."trabalhos" VALUES ('291', 'Photographer');
INSERT INTO "public"."trabalhos" VALUES ('292', 'Production designer, theatre/television/film');
INSERT INTO "public"."trabalhos" VALUES ('293', 'Air traffic controller');
INSERT INTO "public"."trabalhos" VALUES ('294', 'Product designer');
INSERT INTO "public"."trabalhos" VALUES ('295', 'Higher education careers adviser');
INSERT INTO "public"."trabalhos" VALUES ('296', 'Learning mentor');
INSERT INTO "public"."trabalhos" VALUES ('297', 'Computer games developer');
INSERT INTO "public"."trabalhos" VALUES ('298', 'Chartered management accountant');
INSERT INTO "public"."trabalhos" VALUES ('299', 'Lecturer, further education');
INSERT INTO "public"."trabalhos" VALUES ('300', 'Television/film/video producer');
INSERT INTO "public"."trabalhos" VALUES ('301', 'Network engineer');
INSERT INTO "public"."trabalhos" VALUES ('302', 'Administrator, sports');
INSERT INTO "public"."trabalhos" VALUES ('303', 'Printmaker');
INSERT INTO "public"."trabalhos" VALUES ('304', 'Sales promotion account executive');
INSERT INTO "public"."trabalhos" VALUES ('305', 'Toxicologist');
INSERT INTO "public"."trabalhos" VALUES ('306', 'Psychiatric nurse');
INSERT INTO "public"."trabalhos" VALUES ('307', 'Psychologist, occupational');
INSERT INTO "public"."trabalhos" VALUES ('308', 'Hydrographic surveyor');
INSERT INTO "public"."trabalhos" VALUES ('309', 'Administrator, Civil Service');
INSERT INTO "public"."trabalhos" VALUES ('310', 'Programme researcher, broadcasting/film/video');
INSERT INTO "public"."trabalhos" VALUES ('311', 'Arts development officer');
INSERT INTO "public"."trabalhos" VALUES ('312', 'Database administrator');
INSERT INTO "public"."trabalhos" VALUES ('313', 'Barrister');
INSERT INTO "public"."trabalhos" VALUES ('314', 'Financial adviser');
INSERT INTO "public"."trabalhos" VALUES ('315', 'Proofreader');
INSERT INTO "public"."trabalhos" VALUES ('316', 'TEFL teacher');
INSERT INTO "public"."trabalhos" VALUES ('317', 'Corporate treasurer');
INSERT INTO "public"."trabalhos" VALUES ('318', 'Embryologist, clinical');
INSERT INTO "public"."trabalhos" VALUES ('319', 'Nature conservation officer');
INSERT INTO "public"."trabalhos" VALUES ('320', 'Physicist, medical');
INSERT INTO "public"."trabalhos" VALUES ('321', 'Nutritional therapist');
INSERT INTO "public"."trabalhos" VALUES ('322', 'Commercial/residential surveyor');
INSERT INTO "public"."trabalhos" VALUES ('323', 'Museum/gallery curator');
INSERT INTO "public"."trabalhos" VALUES ('324', 'Public relations officer');
INSERT INTO "public"."trabalhos" VALUES ('325', 'Media planner');
INSERT INTO "public"."trabalhos" VALUES ('326', 'Primary school teacher');
INSERT INTO "public"."trabalhos" VALUES ('327', 'Herpetologist');
INSERT INTO "public"."trabalhos" VALUES ('328', 'Fish farm manager');
INSERT INTO "public"."trabalhos" VALUES ('329', 'Engineer, civil (contracting)');
INSERT INTO "public"."trabalhos" VALUES ('330', 'Theme park manager');
INSERT INTO "public"."trabalhos" VALUES ('331', 'Engineer, technical sales');
INSERT INTO "public"."trabalhos" VALUES ('332', 'Presenter, broadcasting');
INSERT INTO "public"."trabalhos" VALUES ('333', 'Radio broadcast assistant');
INSERT INTO "public"."trabalhos" VALUES ('334', 'Environmental manager');
INSERT INTO "public"."trabalhos" VALUES ('335', 'Newspaper journalist');
INSERT INTO "public"."trabalhos" VALUES ('336', 'Sales executive');
INSERT INTO "public"."trabalhos" VALUES ('337', 'Scientist, clinical (histocompatibility and immunogenetics)');
INSERT INTO "public"."trabalhos" VALUES ('338', 'Development worker, community');
INSERT INTO "public"."trabalhos" VALUES ('339', 'Mining engineer');
INSERT INTO "public"."trabalhos" VALUES ('340', 'Multimedia specialist');
INSERT INTO "public"."trabalhos" VALUES ('341', 'Recycling officer');
INSERT INTO "public"."trabalhos" VALUES ('342', 'Medical illustrator');
INSERT INTO "public"."trabalhos" VALUES ('343', 'Therapeutic radiographer');
INSERT INTO "public"."trabalhos" VALUES ('344', 'Lighting technician, broadcasting/film/video');
INSERT INTO "public"."trabalhos" VALUES ('345', 'Clinical scientist, histocompatibility and immunogenetics');
INSERT INTO "public"."trabalhos" VALUES ('346', 'Therapist, horticultural');
INSERT INTO "public"."trabalhos" VALUES ('347', 'Accountant, chartered');
INSERT INTO "public"."trabalhos" VALUES ('348', 'Forest/woodland manager');
INSERT INTO "public"."trabalhos" VALUES ('349', 'Actor');
INSERT INTO "public"."trabalhos" VALUES ('350', 'Seismic interpreter');
INSERT INTO "public"."trabalhos" VALUES ('351', 'Housing manager/officer');
INSERT INTO "public"."trabalhos" VALUES ('352', 'Geoscientist');
INSERT INTO "public"."trabalhos" VALUES ('353', 'Geographical information systems officer');
INSERT INTO "public"."trabalhos" VALUES ('354', 'Agricultural engineer');
INSERT INTO "public"."trabalhos" VALUES ('355', 'Civil Service administrator');
INSERT INTO "public"."trabalhos" VALUES ('356', 'Careers information officer');
INSERT INTO "public"."trabalhos" VALUES ('357', 'Armed forces training and education officer');
INSERT INTO "public"."trabalhos" VALUES ('358', 'Adult guidance worker');
INSERT INTO "public"."trabalhos" VALUES ('359', 'Occupational psychologist');
INSERT INTO "public"."trabalhos" VALUES ('360', 'Programmer, multimedia');
INSERT INTO "public"."trabalhos" VALUES ('361', 'Publishing copy');
INSERT INTO "public"."trabalhos" VALUES ('362', 'Scientist, research (life sciences)');
INSERT INTO "public"."trabalhos" VALUES ('363', 'Call centre manager');
INSERT INTO "public"."trabalhos" VALUES ('364', 'Company secretary');
INSERT INTO "public"."trabalhos" VALUES ('365', 'Tourist information centre manager');
INSERT INTO "public"."trabalhos" VALUES ('366', 'Hospital pharmacist');
INSERT INTO "public"."trabalhos" VALUES ('367', 'Administrator, charities/voluntary organisations');
INSERT INTO "public"."trabalhos" VALUES ('368', 'Air cabin crew');
INSERT INTO "public"."trabalhos" VALUES ('369', 'Operations geologist');
INSERT INTO "public"."trabalhos" VALUES ('370', 'Ceramics designer');
INSERT INTO "public"."trabalhos" VALUES ('371', 'Ergonomist');
INSERT INTO "public"."trabalhos" VALUES ('372', 'Editor, film/video');
INSERT INTO "public"."trabalhos" VALUES ('373', 'Engineer, materials');
INSERT INTO "public"."trabalhos" VALUES ('374', 'Radiographer, diagnostic');
INSERT INTO "public"."trabalhos" VALUES ('375', 'Chemist, analytical');
INSERT INTO "public"."trabalhos" VALUES ('376', 'Dentist');
INSERT INTO "public"."trabalhos" VALUES ('377', 'Social worker');
INSERT INTO "public"."trabalhos" VALUES ('378', 'Geochemist');
INSERT INTO "public"."trabalhos" VALUES ('379', 'Farm manager');
INSERT INTO "public"."trabalhos" VALUES ('380', 'Podiatrist');
INSERT INTO "public"."trabalhos" VALUES ('381', 'Conservator, furniture');
INSERT INTO "public"."trabalhos" VALUES ('382', 'Retail merchandiser');
INSERT INTO "public"."trabalhos" VALUES ('383', 'Careers adviser');
INSERT INTO "public"."trabalhos" VALUES ('384', 'Hydrogeologist');
INSERT INTO "public"."trabalhos" VALUES ('385', 'Advertising account planner');
INSERT INTO "public"."trabalhos" VALUES ('386', 'Comptroller');
INSERT INTO "public"."trabalhos" VALUES ('387', 'Land');
INSERT INTO "public"."trabalhos" VALUES ('388', 'Education officer, museum');
INSERT INTO "public"."trabalhos" VALUES ('389', 'Diagnostic radiographer');
INSERT INTO "public"."trabalhos" VALUES ('390', 'Fisheries officer');
INSERT INTO "public"."trabalhos" VALUES ('391', 'Financial planner');
INSERT INTO "public"."trabalhos" VALUES ('392', 'Tree surgeon');
INSERT INTO "public"."trabalhos" VALUES ('393', 'Quarry manager');
INSERT INTO "public"."trabalhos" VALUES ('394', 'Civil engineer, contracting');
INSERT INTO "public"."trabalhos" VALUES ('395', 'Education officer, community');
INSERT INTO "public"."trabalhos" VALUES ('396', 'Scientific laboratory technician');
INSERT INTO "public"."trabalhos" VALUES ('397', 'Surveyor, hydrographic');
INSERT INTO "public"."trabalhos" VALUES ('398', 'Biomedical scientist');
INSERT INTO "public"."trabalhos" VALUES ('399', 'Engineer, control and instrumentation');
INSERT INTO "public"."trabalhos" VALUES ('400', 'Print production planner');
INSERT INTO "public"."trabalhos" VALUES ('401', 'Clinical biochemist');
INSERT INTO "public"."trabalhos" VALUES ('402', 'Editor, commissioning');
INSERT INTO "public"."trabalhos" VALUES ('403', 'Logistics and distribution manager');
INSERT INTO "public"."trabalhos" VALUES ('404', 'Radiographer, therapeutic');
INSERT INTO "public"."trabalhos" VALUES ('405', 'Associate Professor');
INSERT INTO "public"."trabalhos" VALUES ('406', 'Investment analyst');
INSERT INTO "public"."trabalhos" VALUES ('407', 'Chartered loss adjuster');
INSERT INTO "public"."trabalhos" VALUES ('408', 'Clothing/textile technologist');
INSERT INTO "public"."trabalhos" VALUES ('409', 'Engineer, manufacturing systems');
INSERT INTO "public"."trabalhos" VALUES ('410', 'Investment banker, corporate');
INSERT INTO "public"."trabalhos" VALUES ('411', 'Film/video editor');
INSERT INTO "public"."trabalhos" VALUES ('412', 'Regulatory affairs officer');
INSERT INTO "public"."trabalhos" VALUES ('413', 'Landscape architect');
INSERT INTO "public"."trabalhos" VALUES ('414', 'Accountant, chartered management');
INSERT INTO "public"."trabalhos" VALUES ('415', 'Sports administrator');
INSERT INTO "public"."trabalhos" VALUES ('416', 'Land/geomatics surveyor');
INSERT INTO "public"."trabalhos" VALUES ('417', 'Trading standards officer');
INSERT INTO "public"."trabalhos" VALUES ('418', 'Ophthalmologist');
INSERT INTO "public"."trabalhos" VALUES ('419', 'Designer, jewellery');
INSERT INTO "public"."trabalhos" VALUES ('420', 'Clinical research associate');
INSERT INTO "public"."trabalhos" VALUES ('421', 'Medical technical officer');
INSERT INTO "public"."trabalhos" VALUES ('422', 'Psychiatrist');
INSERT INTO "public"."trabalhos" VALUES ('423', 'Learning disability nurse');
INSERT INTO "public"."trabalhos" VALUES ('424', 'Health service manager');
INSERT INTO "public"."trabalhos" VALUES ('425', 'Wellsite geologist');
INSERT INTO "public"."trabalhos" VALUES ('426', 'Research scientist (maths)');
INSERT INTO "public"."trabalhos" VALUES ('427', 'Stage manager');
INSERT INTO "public"."trabalhos" VALUES ('428', 'Government social research officer');
INSERT INTO "public"."trabalhos" VALUES ('429', 'Television floor manager');
INSERT INTO "public"."trabalhos" VALUES ('430', 'Television production assistant');
INSERT INTO "public"."trabalhos" VALUES ('431', 'Chemical engineer');
INSERT INTO "public"."trabalhos" VALUES ('432', 'Records manager');
INSERT INTO "public"."trabalhos" VALUES ('433', 'Nurse, adult');
INSERT INTO "public"."trabalhos" VALUES ('434', 'Market researcher');
INSERT INTO "public"."trabalhos" VALUES ('435', 'Immunologist');
INSERT INTO "public"."trabalhos" VALUES ('436', 'Public librarian');
INSERT INTO "public"."trabalhos" VALUES ('437', 'Trade mark attorney');
INSERT INTO "public"."trabalhos" VALUES ('438', 'Equality and diversity officer');
INSERT INTO "public"."trabalhos" VALUES ('439', 'Field trials officer');
INSERT INTO "public"."trabalhos" VALUES ('440', 'Solicitor');
INSERT INTO "public"."trabalhos" VALUES ('441', 'Music therapist');
INSERT INTO "public"."trabalhos" VALUES ('442', 'Chief of Staff');
INSERT INTO "public"."trabalhos" VALUES ('443', 'Paramedic');
INSERT INTO "public"."trabalhos" VALUES ('444', 'Clinical molecular geneticist');
INSERT INTO "public"."trabalhos" VALUES ('445', 'Therapist, music');
INSERT INTO "public"."trabalhos" VALUES ('446', 'Designer, television/film set');
INSERT INTO "public"."trabalhos" VALUES ('447', 'Secondary school teacher');
INSERT INTO "public"."trabalhos" VALUES ('448', 'Pilot, airline');
INSERT INTO "public"."trabalhos" VALUES ('449', 'Psychologist, prison and probation services');
INSERT INTO "public"."trabalhos" VALUES ('450', 'Data processing manager');
INSERT INTO "public"."trabalhos" VALUES ('451', 'Science writer');
INSERT INTO "public"."trabalhos" VALUES ('452', 'Set designer');
INSERT INTO "public"."trabalhos" VALUES ('453', 'English as a foreign language teacher');
INSERT INTO "public"."trabalhos" VALUES ('454', 'Surveyor, commercial/residential');
INSERT INTO "public"."trabalhos" VALUES ('455', 'Public house manager');
INSERT INTO "public"."trabalhos" VALUES ('456', 'Arboriculturist');
INSERT INTO "public"."trabalhos" VALUES ('457', 'Tax inspector');
INSERT INTO "public"."trabalhos" VALUES ('458', 'Minerals surveyor');
INSERT INTO "public"."trabalhos" VALUES ('459', 'Restaurant manager, fast food');
INSERT INTO "public"."trabalhos" VALUES ('460', 'Programmer, systems');
INSERT INTO "public"."trabalhos" VALUES ('461', 'Electrical engineer');
INSERT INTO "public"."trabalhos" VALUES ('462', 'Commercial horticulturist');
INSERT INTO "public"."trabalhos" VALUES ('463', 'Pharmacologist');
INSERT INTO "public"."trabalhos" VALUES ('464', 'Aid worker');
INSERT INTO "public"."trabalhos" VALUES ('465', 'Librarian, public');
INSERT INTO "public"."trabalhos" VALUES ('466', 'Sport and exercise psychologist');
INSERT INTO "public"."trabalhos" VALUES ('467', 'Biochemist, clinical');
INSERT INTO "public"."trabalhos" VALUES ('468', 'Engineer, communications');
INSERT INTO "public"."trabalhos" VALUES ('469', 'Water engineer');
INSERT INTO "public"."trabalhos" VALUES ('470', 'Probation officer');
INSERT INTO "public"."trabalhos" VALUES ('471', 'Technical sales engineer');
INSERT INTO "public"."trabalhos" VALUES ('472', 'Town planner');
INSERT INTO "public"."trabalhos" VALUES ('473', 'Surveyor, minerals');
INSERT INTO "public"."trabalhos" VALUES ('474', 'Systems analyst');
INSERT INTO "public"."trabalhos" VALUES ('475', 'Paediatric nurse');
INSERT INTO "public"."trabalhos" VALUES ('476', 'Catering manager');
INSERT INTO "public"."trabalhos" VALUES ('477', 'Journalist, magazine');
INSERT INTO "public"."trabalhos" VALUES ('478', 'Barista');
INSERT INTO "public"."trabalhos" VALUES ('479', 'Engineering geologist');
INSERT INTO "public"."trabalhos" VALUES ('480', 'Building surveyor');
INSERT INTO "public"."trabalhos" VALUES ('481', 'Loss adjuster, chartered');
INSERT INTO "public"."trabalhos" VALUES ('482', 'Engineer, biomedical');
INSERT INTO "public"."trabalhos" VALUES ('483', 'Equities trader');
INSERT INTO "public"."trabalhos" VALUES ('484', 'Merchandiser, retail');
INSERT INTO "public"."trabalhos" VALUES ('485', 'Therapist, sports');
INSERT INTO "public"."trabalhos" VALUES ('486', 'Therapist, art');
INSERT INTO "public"."trabalhos" VALUES ('487', 'Lexicographer');
INSERT INTO "public"."trabalhos" VALUES ('488', 'Administrator, local government');
INSERT INTO "public"."trabalhos" VALUES ('489', 'Health and safety adviser');
INSERT INTO "public"."trabalhos" VALUES ('490', 'IT sales professional');
INSERT INTO "public"."trabalhos" VALUES ('491', 'Commercial art gallery manager');
INSERT INTO "public"."trabalhos" VALUES ('492', 'Engineer, structural');
INSERT INTO "public"."trabalhos" VALUES ('493', 'Occupational hygienist');
INSERT INTO "public"."trabalhos" VALUES ('494', 'Jewellery designer');
INSERT INTO "public"."trabalhos" VALUES ('495', 'Theatre director');
INSERT INTO "public"."trabalhos" VALUES ('496', 'Administrator, arts');
INSERT INTO "public"."trabalhos" VALUES ('497', 'Education officer, environmental');
INSERT INTO "public"."trabalhos" VALUES ('498', 'Charity fundraiser');
INSERT INTO "public"."trabalhos" VALUES ('499', 'Counsellor');
INSERT INTO "public"."trabalhos" VALUES ('500', 'Animal nutritionist');
INSERT INTO "public"."trabalhos" VALUES ('501', 'Community arts worker');
INSERT INTO "public"."trabalhos" VALUES ('502', 'Archivist');
INSERT INTO "public"."trabalhos" VALUES ('503', 'Waste management officer');
INSERT INTO "public"."trabalhos" VALUES ('504', 'Teacher, English as a foreign language');
INSERT INTO "public"."trabalhos" VALUES ('505', 'Geologist, engineering');
INSERT INTO "public"."trabalhos" VALUES ('506', 'Academic librarian');
INSERT INTO "public"."trabalhos" VALUES ('507', 'Cartographer');
INSERT INTO "public"."trabalhos" VALUES ('508', 'Administrator, education');
INSERT INTO "public"."trabalhos" VALUES ('509', 'Tax adviser');
INSERT INTO "public"."trabalhos" VALUES ('510', 'Outdoor activities/education manager');
INSERT INTO "public"."trabalhos" VALUES ('511', 'Information systems manager');
INSERT INTO "public"."trabalhos" VALUES ('512', 'Optician, dispensing');
INSERT INTO "public"."trabalhos" VALUES ('513', 'Conservation officer, historic buildings');
INSERT INTO "public"."trabalhos" VALUES ('514', 'Dispensing optician');
INSERT INTO "public"."trabalhos" VALUES ('515', 'Advertising art director');
INSERT INTO "public"."trabalhos" VALUES ('516', 'Copy');
INSERT INTO "public"."trabalhos" VALUES ('517', 'Accommodation manager');
INSERT INTO "public"."trabalhos" VALUES ('518', 'Clinical cytogeneticist');
INSERT INTO "public"."trabalhos" VALUES ('519', 'Merchant navy officer');
INSERT INTO "public"."trabalhos" VALUES ('520', 'Graphic designer');
INSERT INTO "public"."trabalhos" VALUES ('521', 'Insurance account manager');
INSERT INTO "public"."trabalhos" VALUES ('522', 'Orthoptist');
INSERT INTO "public"."trabalhos" VALUES ('523', 'Programmer, applications');
INSERT INTO "public"."trabalhos" VALUES ('524', 'Producer, television/film/video');
INSERT INTO "public"."trabalhos" VALUES ('525', 'Medical sales representative');
INSERT INTO "public"."trabalhos" VALUES ('526', 'Accountant, chartered certified');
INSERT INTO "public"."trabalhos" VALUES ('527', 'Research officer, political party');
INSERT INTO "public"."trabalhos" VALUES ('528', 'Legal secretary');
INSERT INTO "public"."trabalhos" VALUES ('529', 'Amenity horticulturist');
INSERT INTO "public"."trabalhos" VALUES ('530', 'Armed forces logistics/support/administrative officer');
INSERT INTO "public"."trabalhos" VALUES ('531', 'Firefighter');
INSERT INTO "public"."trabalhos" VALUES ('532', 'Surveyor, insurance');
INSERT INTO "public"."trabalhos" VALUES ('533', 'Interior and spatial designer');
INSERT INTO "public"."trabalhos" VALUES ('534', 'Warehouse manager');
INSERT INTO "public"."trabalhos" VALUES ('535', 'Dietitian');
INSERT INTO "public"."trabalhos" VALUES ('536', 'Runner, broadcasting/film/video');
INSERT INTO "public"."trabalhos" VALUES ('537', 'Plant breeder/geneticist');
INSERT INTO "public"."trabalhos" VALUES ('538', 'Ambulance person');
INSERT INTO "public"."trabalhos" VALUES ('539', 'Engineer, petroleum');
INSERT INTO "public"."trabalhos" VALUES ('540', 'Furniture designer');
INSERT INTO "public"."trabalhos" VALUES ('541', 'Osteopath');
INSERT INTO "public"."trabalhos" VALUES ('542', 'Purchasing manager');
INSERT INTO "public"."trabalhos" VALUES ('543', 'Biomedical engineer');
INSERT INTO "public"."trabalhos" VALUES ('544', 'Location manager');
INSERT INTO "public"."trabalhos" VALUES ('545', 'Retail manager');
INSERT INTO "public"."trabalhos" VALUES ('546', 'Advertising account executive');
INSERT INTO "public"."trabalhos" VALUES ('547', 'Engineer, mining');
INSERT INTO "public"."trabalhos" VALUES ('548', 'Insurance risk surveyor');
INSERT INTO "public"."trabalhos" VALUES ('549', 'Manufacturing engineer');
INSERT INTO "public"."trabalhos" VALUES ('550', 'Field seismologist');
INSERT INTO "public"."trabalhos" VALUES ('551', 'Chartered certified accountant');
INSERT INTO "public"."trabalhos" VALUES ('552', 'Phytotherapist');
INSERT INTO "public"."trabalhos" VALUES ('553', 'Fashion designer');
INSERT INTO "public"."trabalhos" VALUES ('554', 'Scientist, forensic');
INSERT INTO "public"."trabalhos" VALUES ('555', 'Nurse, children''s');
INSERT INTO "public"."trabalhos" VALUES ('556', 'Technical author');
INSERT INTO "public"."trabalhos" VALUES ('557', 'Trade union research officer');
INSERT INTO "public"."trabalhos" VALUES ('558', 'Advice worker');
INSERT INTO "public"."trabalhos" VALUES ('559', 'Dancer');
INSERT INTO "public"."trabalhos" VALUES ('560', 'Site engineer');
INSERT INTO "public"."trabalhos" VALUES ('561', 'Marketing executive');
INSERT INTO "public"."trabalhos" VALUES ('562', 'Quality manager');
INSERT INTO "public"."trabalhos" VALUES ('563', 'Surveyor, land/geomatics');
INSERT INTO "public"."trabalhos" VALUES ('564', 'Building services engineer');
INSERT INTO "public"."trabalhos" VALUES ('565', 'Psychologist, educational');
INSERT INTO "public"."trabalhos" VALUES ('566', 'Sales professional, IT');
INSERT INTO "public"."trabalhos" VALUES ('567', 'Community development worker');
INSERT INTO "public"."trabalhos" VALUES ('568', 'Clinical psychologist');
INSERT INTO "public"."trabalhos" VALUES ('569', 'Telecommunications researcher');
INSERT INTO "public"."trabalhos" VALUES ('570', 'Theatre stage manager');
INSERT INTO "public"."trabalhos" VALUES ('571', 'Archaeologist');
INSERT INTO "public"."trabalhos" VALUES ('572', 'Games developer');
INSERT INTO "public"."trabalhos" VALUES ('573', 'Therapist, drama');
INSERT INTO "public"."trabalhos" VALUES ('574', 'Tourism officer');
INSERT INTO "public"."trabalhos" VALUES ('575', 'Engineer, electronics');
INSERT INTO "public"."trabalhos" VALUES ('576', 'Soil scientist');
INSERT INTO "public"."trabalhos" VALUES ('577', 'Psychologist, clinical');
INSERT INTO "public"."trabalhos" VALUES ('578', 'Engineer, broadcasting (operations)');
INSERT INTO "public"."trabalhos" VALUES ('579', 'Statistician');
INSERT INTO "public"."trabalhos" VALUES ('580', 'Journalist, broadcasting');
INSERT INTO "public"."trabalhos" VALUES ('581', 'Fitness centre manager');
INSERT INTO "public"."trabalhos" VALUES ('582', 'Production engineer');
INSERT INTO "public"."trabalhos" VALUES ('583', 'Barrister''s clerk');
INSERT INTO "public"."trabalhos" VALUES ('584', 'Medical laboratory scientific officer');
INSERT INTO "public"."trabalhos" VALUES ('585', 'Community education officer');
INSERT INTO "public"."trabalhos" VALUES ('586', 'Management consultant');
INSERT INTO "public"."trabalhos" VALUES ('587', 'Teacher, early years/pre');
INSERT INTO "public"."trabalhos" VALUES ('588', 'Lobbyist');
INSERT INTO "public"."trabalhos" VALUES ('589', 'Engineer, agricultural');
INSERT INTO "public"."trabalhos" VALUES ('590', 'Psychotherapist');
INSERT INTO "public"."trabalhos" VALUES ('591', 'Animal technologist');
INSERT INTO "public"."trabalhos" VALUES ('592', 'Insurance underwriter');
INSERT INTO "public"."trabalhos" VALUES ('593', 'Corporate investment banker');
INSERT INTO "public"."trabalhos" VALUES ('594', 'Conservation officer, nature');
INSERT INTO "public"."trabalhos" VALUES ('595', 'Armed forces technical officer');
INSERT INTO "public"."trabalhos" VALUES ('596', 'Exhibitions officer, museum/gallery');
INSERT INTO "public"."trabalhos" VALUES ('597', 'Glass blower/designer');
INSERT INTO "public"."trabalhos" VALUES ('598', 'Estate agent');
INSERT INTO "public"."trabalhos" VALUES ('599', 'Meteorologist');
INSERT INTO "public"."trabalhos" VALUES ('600', 'Solicitor, Scotland');
INSERT INTO "public"."trabalhos" VALUES ('601', 'Forensic psychologist');
INSERT INTO "public"."trabalhos" VALUES ('602', 'Nurse, learning disability');
INSERT INTO "public"."trabalhos" VALUES ('603', 'Pharmacist, hospital');
INSERT INTO "public"."trabalhos" VALUES ('604', 'Intelligence analyst');
INSERT INTO "public"."trabalhos" VALUES ('605', 'Mechanical engineer');
INSERT INTO "public"."trabalhos" VALUES ('606', 'Magazine features editor');
INSERT INTO "public"."trabalhos" VALUES ('607', 'Facilities manager');
INSERT INTO "public"."trabalhos" VALUES ('608', 'Scientist, audiological');
INSERT INTO "public"."trabalhos" VALUES ('609', 'Airline pilot');
INSERT INTO "public"."trabalhos" VALUES ('610', 'Engineer, electrical');
INSERT INTO "public"."trabalhos" VALUES ('611', 'Physiological scientist');
INSERT INTO "public"."trabalhos" VALUES ('612', 'Structural engineer');
INSERT INTO "public"."trabalhos" VALUES ('613', 'Accounting technician');
INSERT INTO "public"."trabalhos" VALUES ('614', 'Warden/ranger');
INSERT INTO "public"."trabalhos" VALUES ('615', 'Production manager');
INSERT INTO "public"."trabalhos" VALUES ('616', 'Scientist, product/process development');
INSERT INTO "public"."trabalhos" VALUES ('617', 'Hydrologist');
INSERT INTO "public"."trabalhos" VALUES ('618', 'Leisure centre manager');
INSERT INTO "public"."trabalhos" VALUES ('619', 'Race relations officer');
INSERT INTO "public"."trabalhos" VALUES ('620', 'Textile designer');
INSERT INTO "public"."trabalhos" VALUES ('621', 'Geneticist, molecular');
INSERT INTO "public"."trabalhos" VALUES ('622', 'Special effects artist');
INSERT INTO "public"."trabalhos" VALUES ('623', 'Ranger/warden');
INSERT INTO "public"."trabalhos" VALUES ('624', 'Teacher, secondary school');
INSERT INTO "public"."trabalhos" VALUES ('625', 'Pension scheme manager');
INSERT INTO "public"."trabalhos" VALUES ('626', 'Engineer, site');
INSERT INTO "public"."trabalhos" VALUES ('627', 'Exhibition designer');
INSERT INTO "public"."trabalhos" VALUES ('628', 'Naval architect');
INSERT INTO "public"."trabalhos" VALUES ('629', 'Dealer');
INSERT INTO "public"."trabalhos" VALUES ('630', 'Food technologist');
INSERT INTO "public"."trabalhos" VALUES ('631', 'Designer, textile');
INSERT INTO "public"."trabalhos" VALUES ('632', 'Magazine journalist');
INSERT INTO "public"."trabalhos" VALUES ('633', 'Prison officer');
INSERT INTO "public"."trabalhos" VALUES ('634', 'Designer, fashion/clothing');
INSERT INTO "public"."trabalhos" VALUES ('635', 'Theatre manager');
INSERT INTO "public"."trabalhos" VALUES ('636', 'Veterinary surgeon');
INSERT INTO "public"."trabalhos" VALUES ('637', 'Investment banker, operational');
INSERT INTO "public"."trabalhos" VALUES ('638', 'Broadcast presenter');
INSERT INTO "public"."trabalhos" VALUES ('639', 'Applications developer');
INSERT INTO "public"."trabalhos" VALUES ('640', 'Politician''s assistant');
INSERT INTO "public"."trabalhos" VALUES ('641', 'Health and safety inspector');
INSERT INTO "public"."trabalhos" VALUES ('642', 'Lecturer, higher education');

-- ----------------------------
-- Alter Sequences Owned By 
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table trabalhos
-- ----------------------------
ALTER TABLE "public"."trabalhos" ADD PRIMARY KEY ("id");
